"""Orquestador: imagen → 3MF multiparte validado."""

from __future__ import annotations

import json
import os
import time
from dataclasses import dataclass

from .config import COMMUNITY_MAX_COLORS, TokenSpec
from .layers import LayerStack, build_stack
from .mesh import mesh_stats, recenter, stack_to_meshes
from .raster import load_image, masks_from_index, quantize
from .threemf import write_3mf
from .validate import ValidationReport, validate_stack
from .vectorize import HAVE_VTRACER, trace_mask

__all__ = ["PipelineResult", "run"]


@dataclass
class PipelineResult:
    stack: LayerStack
    report: ValidationReport
    meshes: list
    outputs: dict[str, str]
    timings: dict[str, float]


def run(
    image_path: str,
    outdir: str,
    spec: TokenSpec,
    max_px: int = 900,
    despeckle_px: int = 6,
    drop_background: bool = True,
    write_preview: bool = True,
    on_log=print,
) -> PipelineResult:
    os.makedirs(outdir, exist_ok=True)
    t: dict[str, float] = {}
    clock = time.perf_counter

    if spec.colors > COMMUNITY_MAX_COLORS:
        on_log(
            f"  ! Community Edition: {spec.colors} colores solicitados, se limita a "
            f"{COMMUNITY_MAX_COLORS}. La edición completa no tiene tope."
        )
        spec.colors = COMMUNITY_MAX_COLORS

    # 1 — raster ------------------------------------------------------------
    s = clock()
    img, mask = load_image(image_path, max_px=max_px, drop_background=drop_background)
    q = quantize(img, mask, spec.colors, palette=list(spec.palette) if spec.palette else None,
                 despeckle_px=despeckle_px)
    t["raster"] = clock() - s
    on_log(f"  1/6 raster        {img.size[0]}×{img.size[1]} px → {len(q.used_indices)} colores")

    # 2 — vectorización -----------------------------------------------------
    s = clock()
    mm_per_px = spec.width_mm / img.size[0]
    geoms = {}
    for idx, m in masks_from_index(q).items():
        g = trace_mask(m, mm_per_px, simplify_mm=spec.simplify_mm)
        if not g.is_empty:
            geoms[idx] = g
    t["vectorize"] = clock() - s
    engine = "vtracer" if HAVE_VTRACER else "respaldo numpy"
    rings = sum(1 + len(p.interiors) for g in geoms.values() for p in g.geoms)
    on_log(f"  2/6 vectorizado   {engine}: {rings} contornos, {mm_per_px:.4f} mm/px")

    # 3 — unión acumulativa -------------------------------------------------
    s = clock()
    stack = build_stack(geoms, q.colors, spec, filaments=q.filaments)
    t["layers"] = clock() - s
    on_log(
        f"  3/6 unión acum.   {len(stack.layers)} capas; "
        f"{stack.absorbed_mm2:.3f} mm² absorbidos, {stack.overlap_removed_mm2:.3f} mm² de solape"
    )

    # 4 — validación --------------------------------------------------------
    s = clock()
    report = validate_stack(stack)
    t["validate"] = clock() - s
    on_log(f"  4/6 validación    {len(report.errors)} errores, {len(report.warnings)} avisos")

    # 5 — malla -------------------------------------------------------------
    s = clock()
    meshes = stack_to_meshes(stack)
    recenter(meshes)
    ms = mesh_stats(meshes)
    t["mesh"] = clock() - s
    on_log(
        f"  5/6 malla         {ms['parts']} partes, {ms['triangles']} triángulos, "
        f"estanca={ms['watertight']}, ≈{ms['estimated_grams']} g"
    )

    # 6 — exportación -------------------------------------------------------
    s = clock()
    stem = os.path.splitext(os.path.basename(image_path))[0]
    outputs: dict[str, str] = {}

    path_3mf = os.path.join(outdir, f"{stem}.3mf")
    write_3mf(
        path_3mf,
        [(l.name, m, l.rgb) for l, m in meshes],
        metadata={
            "Title": stem,
            "Description": f"TokenGen {spec.mode} · {len(meshes)} colores · {spec.width_mm} mm",
            "LicenseTerms": "Generated by TokenGen Community Edition",
        },
    )
    outputs["3mf"] = path_3mf

    report_path = os.path.join(outdir, f"{stem}.report.json")
    with open(report_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "input": os.path.basename(image_path),
                "spec": spec.to_dict(),
                "mesh": ms,
                "timings_s": {k: round(v, 3) for k, v in t.items()},
                "validation": report.to_dict(),
                "layers": [
                    {
                        "name": l.name,
                        "rgb": list(l.rgb),
                        "area_mm2": round(l.area_mm2, 3),
                        "z": [round(l.z0, 3), round(l.z1, 3)],
                        "ams_slot": l.filament.slot if l.filament else None,
                    }
                    for l in stack.layers
                ],
            },
            f, indent=2, ensure_ascii=False,
        )
    outputs["report"] = report_path

    if write_preview:
        from .preview import render_topdown, write_three_html

        outputs["preview_png"] = render_topdown(stack, os.path.join(outdir, f"{stem}.preview.png"))
        outputs["preview_html"] = write_three_html(
            meshes, os.path.join(outdir, f"{stem}.preview.html"), title=stem
        )

    t["export"] = clock() - s
    on_log(f"  6/6 exportado     {os.path.basename(path_3mf)} (+ report.json, preview)")

    return PipelineResult(stack=stack, report=report, meshes=meshes, outputs=outputs, timings=t)
